// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFeZbT1VKfO3V3dq-3or4BPjBM3tAOkRg',
    appId: '1:440388684307:web:f7549467a8117903bccde6',
    messagingSenderId: '440388684307',
    projectId: 'chat-app-e86cf',
    authDomain: 'chat-app-e86cf.firebaseapp.com',
    storageBucket: 'chat-app-e86cf.appspot.com',
    measurementId: 'G-XBRSMP4E1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXu4AisCt3INLc2Rmmjmz_crJK7brvecE',
    appId: '1:440388684307:android:c9f2eb322169eca0bccde6',
    messagingSenderId: '440388684307',
    projectId: 'chat-app-e86cf',
    storageBucket: 'chat-app-e86cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_A7AHdfXu6gQGOaI9P3PC_VQ0fnNOREM',
    appId: '1:440388684307:ios:b030665b8235af26bccde6',
    messagingSenderId: '440388684307',
    projectId: 'chat-app-e86cf',
    storageBucket: 'chat-app-e86cf.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_A7AHdfXu6gQGOaI9P3PC_VQ0fnNOREM',
    appId: '1:440388684307:ios:31019cdd4b55c8fdbccde6',
    messagingSenderId: '440388684307',
    projectId: 'chat-app-e86cf',
    storageBucket: 'chat-app-e86cf.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
